# Generated by Django 2.2.4 on 2019-08-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
